
trigger:
- main

pool: 
 name: dhurander

stages:
  - stage:
    displayName: terraform
    jobs:
    - job: 
      displayName: new
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      # ========================================================
    # TERRAFORM VALIDATE
    # ========================================================
      - task: TerraformTask@5
        displayName: 'Terraform Validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/infradev'